package org.firstinspires.ftc.teamcode.Robot;

import static android.graphics.Bitmap.createBitmap;
import static org.opencv.imgproc.Imgproc.findContours;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.HashMap;

import org.firstinspires.ftc.robotcore.external.Telemetry;
import org.firstinspires.ftc.robotcore.internal.camera.calibration.CameraCalibration;
import org.firstinspires.ftc.vision.VisionProcessor;
import org.opencv.android.Utils;
import org.opencv.core.*;
import org.opencv.core.Core.*;
import org.opencv.imgproc.*;
import org.opencv.objdetect.*;

/**
* SamplePipeline class.
*
* <p>An OpenCV pipeline generated by GRIP.
*
* @author GRIP
*/
public class SamplePipeline implements VisionProcessor
{
    //Outputs
	private Mat cvCvtcolorOutput = new Mat();
	private Mat cvExtractchannelOutput = new Mat();
	private Mat cvThresholdOutput = new Mat();
	private Mat cvErodeOutput = new Mat();
	private Mat cvDilateOutput = new Mat();
	private ArrayList<MatOfPoint> findContoursOutput = new ArrayList<MatOfPoint>();
	private ArrayList<MatOfPoint> convexHullsOutput = new ArrayList<MatOfPoint>();

	Bitmap myBitmap;
	Mat myMat;

	double inittime = 0;
	int index = -1;

	Point[] contourPts;
	long numPts = 0;
	double xPos = 320;
	double yPos = 240;

	String bitmapText = "";

	int numCountours = 0;

	public static int minThreshold = 140;
	public static int maxThreshold = 255;

	public static int erodeSize = 20;

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}


	public void setTelemetry(Telemetry telemetry)
	{
		this.telemetry = telemetry;
	}

	Telemetry telemetry;

	@Override
	public void init(int width, int height, CameraCalibration calibration)
	{
		inittime = System.nanoTime() / 1_000_000_000.0;
	}

	/**
	 * This is the primary method that runs the entire pipeline and updates the outputs.
	 */
	@Override
	public Object processFrame(Mat frame, long captureTimeNanos) {
		// Step CV_cvtColor0:
		Mat cvCvtcolorSrc = frame.rowRange(frame.rows() / 2, frame.rows());  // only bottom half of image
		int cvCvtcolorCode = Imgproc.COLOR_RGB2YCrCb;
		cvCvtcolor(cvCvtcolorSrc, cvCvtcolorCode, cvCvtcolorOutput);

		// Step CV_extractChannel0:
		Mat cvExtractchannelSrc = cvCvtcolorOutput;
		double cvExtractchannelChannel = 1.0;
		cvExtractchannel(cvExtractchannelSrc, cvExtractchannelChannel, cvExtractchannelOutput);

		// Step CV_Threshold0:
		Mat cvThresholdSrc = cvExtractchannelOutput;
		double cvThresholdThresh = 110.0;
		double cvThresholdMaxval = 255.0;
		int cvThresholdType = Imgproc.THRESH_BINARY_INV;
		cvThreshold(cvThresholdSrc, cvThresholdThresh, cvThresholdMaxval, cvThresholdType, cvThresholdOutput);

		// Step CV_erode0:
		Mat cvErodeSrc = cvThresholdOutput;
		Mat cvErodeKernel = new Mat();
		Point cvErodeAnchor = new Point(-1, -1);
		double cvErodeIterations = 12.0;
		int cvErodeBordertype = Core.BORDER_CONSTANT;
		Scalar cvErodeBordervalue = new Scalar(-1);
		cvErode(cvErodeSrc, cvErodeKernel, cvErodeAnchor, cvErodeIterations, cvErodeBordertype, cvErodeBordervalue, cvErodeOutput);

		// Step CV_dilate0:
		Mat cvDilateSrc = cvErodeOutput;
		Mat cvDilateKernel = new Mat();
		Point cvDilateAnchor = new Point(-1, -1);
		double cvDilateIterations = 12.0;
		int cvDilateBordertype = Core.BORDER_CONSTANT;
		Scalar cvDilateBordervalue = new Scalar(-1);
		cvDilate(cvDilateSrc, cvDilateKernel, cvDilateAnchor, cvDilateIterations, cvDilateBordertype, cvDilateBordervalue, cvDilateOutput);

		// Step Find_Contours0:
		Mat findContoursInput = cvDilateOutput;
		boolean findContoursExternalOnly = true;
		findContours(findContoursInput, findContoursExternalOnly, findContoursOutput);

		// Step Convex_Hulls0:
		ArrayList<MatOfPoint> convexHullsContours = findContoursOutput;
		convexHulls(convexHullsContours, convexHullsOutput);

		numCountours = findContoursOutput.size();

		if (numCountours > 0)
		{
			double maxArea = 0;
			int maxIndex = 0;

			for (int i = 0; i < findContoursOutput.size(); i++)
			{
				double currentArea = Imgproc.contourArea(findContoursOutput.get(i));
				if (currentArea > maxArea)
				{
					maxArea = currentArea;
					maxIndex = i;
				}
			}
			contourPts = findContoursOutput.get(maxIndex).toArray();
			numPts = findContoursOutput.get(maxIndex).total();

			// Calculate moments of the contour
			Moments moments = Imgproc.moments(findContoursOutput.get(maxIndex));

			// find X and Y of the centroid of the contour
			xPos = moments.m10 / moments.m00;
			yPos = moments.m01 / moments.m00;


		}
		else
		{
			// Nothing to report
 		}
		return frame;
	}


	@Override
	public void onDrawFrame(Canvas canvas, int onscreenWidth, int onscreenHeight, float scaleBmpPxToCanvasPx, float scaleCanvasDensity, Object userContext)
	{
		if ((System.nanoTime() / 1_000_000_000.0) - inittime > 1)
		{
			index++;
			inittime = System.nanoTime() / 1_000_000_000.0;
		}

		switch (index)
		{
			case 0:
				myMat = cvCvtcolorOutput();
				bitmapText = "New Color";
				break;
			case 1:
				myMat = cvExtractchannelOutput();
				bitmapText = "Extract Channel";
				break;
			case 2:
				myMat = cvThresholdOutput();
				bitmapText = "Threshold";
				break;
			case 3:
				myMat = cvErodeOutput();
				bitmapText = "Erode";
				break;
			case 4:
				myMat = cvDilateOutput();
				bitmapText = "Dilate Again";
				break;
			default:
				index = 0;
				break;
		}

		try
		{
			myBitmap = createBitmap(myMat.width(), myMat.height(), Bitmap.Config.ARGB_8888);

			Utils.matToBitmap(myMat, myBitmap);
			android.graphics.Rect drawRegion = new android.graphics.Rect(0, 0, onscreenWidth, onscreenHeight);
			canvas.drawBitmap(myBitmap, null, drawRegion, null);

			Paint bitmapTextPaint = new Paint();
			bitmapTextPaint.setColor(Color.CYAN);
			bitmapTextPaint.setAntiAlias(true);
			bitmapTextPaint.setTypeface(Typeface.DEFAULT_BOLD);
			bitmapTextPaint.setTextSize(50);
			canvas.drawText(bitmapText, 400, 600, bitmapTextPaint);

			Paint textPaint = new Paint();
			textPaint.setColor(Color.CYAN);
			textPaint.setAntiAlias(true);
			textPaint.setTypeface(Typeface.DEFAULT_BOLD);
			textPaint.setTextSize(50);
			canvas.drawText("X: " + String.valueOf(xPos), 100, 450, textPaint);
			canvas.drawText("Y: " + String.valueOf(yPos), 300, 450, textPaint);

			Paint circlePaint = new Paint();
			circlePaint.setColor(Color.CYAN);
			circlePaint.setStrokeWidth(5);
			canvas.drawCircle((float) xPos, (float) yPos, 50, circlePaint);

			Paint contourPaint = new Paint();
			contourPaint.setColor(Color.MAGENTA);
			contourPaint.setStrokeWidth(10);

			if (contourPts != null)
			{
				for (int j = 0; j < numPts; j++)
				{
					canvas.drawPoint((float) contourPts[j].x, (float) contourPts[j].y,
							contourPaint);
				}
			}
		}
		catch (Exception e)
		{
			telemetry.addData("myMat: ", bitmapText);
			telemetry.update();
		}
	}


	/**
	 * This method is a generated getter for the output of a CV_cvtColor.
	 * @return Mat output from CV_cvtColor.
	 */
	public Mat cvCvtcolorOutput() {
		return cvCvtcolorOutput;
	}

	/**
	 * This method is a generated getter for the output of a CV_extractChannel.
	 * @return Mat output from CV_extractChannel.
	 */
	public Mat cvExtractchannelOutput() {
		return cvExtractchannelOutput;
	}

	/**
	 * This method is a generated getter for the output of a CV_Threshold.
	 * @return Mat output from CV_Threshold.
	 */
	public Mat cvThresholdOutput() {
		return cvThresholdOutput;
	}

	/**
	 * This method is a generated getter for the output of a CV_erode.
	 * @return Mat output from CV_erode.
	 */
	public Mat cvErodeOutput() {
		return cvErodeOutput;
	}

	/**
	 * This method is a generated getter for the output of a CV_dilate.
	 * @return Mat output from CV_dilate.
	 */
	public Mat cvDilateOutput() {
		return cvDilateOutput;
	}

	/**
	 * This method is a generated getter for the output of a Find_Contours.
	 * @return ArrayList<MatOfPoint> output from Find_Contours.
	 */
	public ArrayList<MatOfPoint> findContoursOutput() {
		return findContoursOutput;
	}

	/**
	 * This method is a generated getter for the output of a Convex_Hulls.
	 * @return ArrayList<MatOfPoint> output from Convex_Hulls.
	 */
	public ArrayList<MatOfPoint> convexHullsOutput() {
		return convexHullsOutput;
	}


	/**
	 * Converts an image from one color space to another.
	 * @param src Image to convert.
	 * @param code conversion code.
	 * @param dst converted Image.
	 */
	private void cvCvtcolor(Mat src, int code, Mat dst) {
		Imgproc.cvtColor(src, dst, code);
	}

	/**
	 * Extracts given channel from an image.
	 * @param src the image to extract.
	 * @param channel zero indexed channel number to extract.
	 * @param dst output image.
	 */
	private void cvExtractchannel(Mat src, double channel, Mat dst) {
		Core.extractChannel(src, dst, (int)channel);
	}

	/**
	 * Apply a fixed-level threshold to each array element in an image.
	 * @param src Image to threshold.
	 * @param threshold threshold value.
	 * @param maxVal Maximum value for THRES_BINARY and THRES_BINARY_INV
	 * @param type Type of threshold to appy.
	 * @param dst output Image.
	 */
	private void cvThreshold(Mat src, double threshold, double maxVal, int type,
		Mat dst) {
		Imgproc.threshold(src, dst, threshold, maxVal, type);
	}

	/**
	 * Expands area of lower value in an image.
	 * @param src the Image to erode.
	 * @param kernel the kernel for erosion.
	 * @param anchor the center of the kernel.
	 * @param iterations the number of times to perform the erosion.
	 * @param borderType pixel extrapolation method.
	 * @param borderValue value to be used for a constant border.
	 * @param dst Output Image.
	 */
	private void cvErode(Mat src, Mat kernel, Point anchor, double iterations,
		int borderType, Scalar borderValue, Mat dst) {
		if (kernel == null) {
			kernel = new Mat();
		}
		if (anchor == null) {
			anchor = new Point(-1,-1);
		}
		if (borderValue == null) {
			borderValue = new Scalar(-1);
		}
		Imgproc.erode(src, dst, kernel, anchor, (int)iterations, borderType, borderValue);
	}

	/**
	 * Expands area of higher value in an image.
	 * @param src the Image to dilate.
	 * @param kernel the kernel for dilation.
	 * @param anchor the center of the kernel.
	 * @param iterations the number of times to perform the dilation.
	 * @param borderType pixel extrapolation method.
	 * @param borderValue value to be used for a constant border.
	 * @param dst Output Image.
	 */
	private void cvDilate(Mat src, Mat kernel, Point anchor, double iterations,
	int borderType, Scalar borderValue, Mat dst) {
		if (kernel == null) {
			kernel = new Mat();
		}
		if (anchor == null) {
			anchor = new Point(-1,-1);
		}
		if (borderValue == null){
			borderValue = new Scalar(-1);
		}
		Imgproc.dilate(src, dst, kernel, anchor, (int)iterations, borderType, borderValue);
	}

	/**
	 * Sets the values of pixels in a binary image to their distance to the nearest black pixel.
	 * @param input The image on which to perform the Distance Transform.
	 */
	private void findContours(Mat input, boolean externalOnly,
		List<MatOfPoint> contours) {
		Mat hierarchy = new Mat();
		contours.clear();
		int mode;
		if (externalOnly) {
			mode = Imgproc.RETR_EXTERNAL;
		}
		else {
			mode = Imgproc.RETR_LIST;
		}
		int method = Imgproc.CHAIN_APPROX_SIMPLE;
		Imgproc.findContours(input, contours, hierarchy, mode, method);
	}

	/**
	 * Compute the convex hulls of contours.
	 * @param inputContours The contours on which to perform the operation.
	 * @param outputContours The contours where the output will be stored.
	 */
	private void convexHulls(List<MatOfPoint> inputContours,
		ArrayList<MatOfPoint> outputContours) {
		final MatOfInt hull = new MatOfInt();
		outputContours.clear();
		for (int i = 0; i < inputContours.size(); i++) {
			final MatOfPoint contour = inputContours.get(i);
			final MatOfPoint mopHull = new MatOfPoint();
			Imgproc.convexHull(contour, hull);
			mopHull.create((int) hull.size().height, 1, CvType.CV_32SC2);
			for (int j = 0; j < hull.size().height; j++) {
				int index = (int) hull.get(j, 0)[0];
				double[] point = new double[] {contour.get(index, 0)[0], contour.get(index, 0)[1]};
				mopHull.put(j, 0, point);
			}
			outputContours.add(mopHull);
		}
	}




}

